/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/conflict-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Conflict */
        post: operations["decide_conflict_api_v1_conflict_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Conversation */
        post: operations["conversation_api_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Messages */
        get: operations["get_messages_api_v1_conversations__conversation_id__messages_get"];
        put?: never;
        /** Send Message */
        post: operations["send_message_api_v1_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Draft */
        post: operations["create_draft_api_v1_drafts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_v1_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Draft */
        patch: operations["patch_draft_api_v1_drafts__draft_id__patch"];
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/clarifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clarify */
        post: operations["clarify_api_v1_drafts__draft_id__clarifications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit Draft */
        post: operations["commit_draft_api_v1_drafts__draft_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/event-change-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Proposal */
        post: operations["change_proposal_api_v1_event_change_proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flexible-task-queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Flexible Query */
        post: operations["flexible_query_api_v1_flexible_task_queries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flexible-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Flexible Task */
        post: operations["flexible_task_api_v1_flexible_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/occurrences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Occurrences */
        get: operations["occurrences_api_v1_occurrences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/occurrences/{occurrence_id}/exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Occurrence Exception */
        post: operations["occurrence_exception_api_v1_occurrences__occurrence_id__exceptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/{reminder_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ack */
        post: operations["ack_api_v1_reminders__reminder_id__ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State */
        get: operations["state_api_v1_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weather */
        get: operations["weather_api_v1_weather_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CandidateOperation */
        CandidateOperation: {
            /**
             * Action
             * @enum {string}
             */
            action: "update_candidate" | "remove_candidate" | "add_candidate";
            /** Candidate Id */
            candidate_id: string | null;
            /** Changes */
            changes: {
                [key: string]: unknown;
            } | null;
        };
        /** ChangeProposalRequest */
        ChangeProposalRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "update" | "delete";
            /** Changes */
            changes: {
                [key: string]: unknown;
            } | null;
            /** Expected Version */
            expected_version: number;
            /**
             * Scope
             * @enum {string}
             */
            scope: "occurrence" | "series";
            /** Source Message Id */
            source_message_id: string;
            /** Target Id */
            target_id: string;
        };
        /** ChangeProposalResponse */
        ChangeProposalResponse: {
            /** Proposal Id */
            proposal_id: string;
            /** Revision */
            revision: number;
            /**
             * Scope
             * @enum {string}
             */
            scope: "occurrence" | "series";
            /** Summary */
            summary: string;
            /** Target Id */
            target_id: string;
        };
        /** ClarificationRequest */
        ClarificationRequest: {
            /** Answers */
            answers: {
                [key: string]: string;
            };
            /** Revision */
            revision: number;
        };
        /** CommittedResource */
        CommittedResource: {
            /** Resource Id */
            resource_id: string;
            /**
             * Resource Type
             * @enum {string}
             */
            resource_type: "event" | "flexible_task";
            /** Version */
            version: number;
        };
        /** Conflict */
        Conflict: {
            /** Conflict Id */
            conflict_id: string;
            /** Member Ids */
            member_ids: string[];
            /** Selected Id */
            selected_id: string | null;
            /** Snapshot Revision */
            snapshot_revision: number;
        };
        /** ConflictDecisionRequest */
        ConflictDecisionRequest: {
            /** Member Ids */
            member_ids: string[];
            /** Selected Id */
            selected_id: string;
            /** Snapshot Revision */
            snapshot_revision: number;
            /** Source Action Id */
            source_action_id: string;
        };
        /** ConflictDecisionResponse */
        ConflictDecisionResponse: {
            /** Affected Occurrences */
            affected_occurrences: components["schemas"]["Occurrence"][];
            /** Decision Id */
            decision_id: string;
            /** Selected Id */
            selected_id: string;
            /** State Revision */
            state_revision: number;
        };
        /** Conversation */
        Conversation: {
            /** Conversation Id */
            conversation_id: string;
            /** Revision */
            revision: number;
        };
        /** ConversationMessage */
        ConversationMessage: {
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Message Id */
            message_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Sequence */
            sequence: number;
        };
        /**
         * Disposition
         * @enum {string}
         */
        Disposition: "scheduled" | "excused" | "cancelled" | "missed";
        /** DraftCandidate */
        DraftCandidate: {
            /** Candidate Id */
            candidate_id: string;
            /** End At */
            end_at: string | null;
            /** Location */
            location: string | null;
            /** Missing Fields */
            missing_fields: string[];
            recurrence: components["schemas"]["Recurrence"] | null;
            /** Start At */
            start_at: string | null;
            /** Timezone */
            timezone: string | null;
            /** Title */
            title: string | null;
        };
        /** DraftCommitRequest */
        DraftCommitRequest: {
            /** Confirmation Digest */
            confirmation_digest: string;
            /** Confirmed Candidate Ids */
            confirmed_candidate_ids: string[];
            /** Conflict Acceptance */
            conflict_acceptance: string | null;
            /** Revision */
            revision: number;
        };
        /** DraftCommitResponse */
        DraftCommitResponse: {
            /** Draft Id */
            draft_id: string;
            /** Resources */
            resources: components["schemas"]["CommittedResource"][];
            /** Revision */
            revision: number;
        };
        /** DraftPatchRequest */
        DraftPatchRequest: {
            /** Operations */
            operations: components["schemas"]["CandidateOperation"][];
            /** Revision */
            revision: number;
        };
        /** DraftRequest */
        DraftRequest: {
            /** Conversation Id */
            conversation_id: string;
            /** Intent */
            intent: string;
            /** Source Message Id */
            source_message_id: string;
            /** Text */
            text: string;
            /** Timezone */
            timezone: string;
        };
        /** DraftResponse */
        DraftResponse: {
            /** Candidates */
            candidates: components["schemas"]["DraftCandidate"][];
            /** Confirmation Digest */
            confirmation_digest: string | null;
            /** Draft Id */
            draft_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Questions */
            questions: string[];
            /**
             * Reference Now
             * Format: date-time
             */
            reference_now: string;
            /** Related Action Ids */
            related_action_ids: string[];
            /** Revision */
            revision: number;
            status: components["schemas"]["DraftStatus"];
        };
        /**
         * DraftStatus
         * @enum {string}
         */
        DraftStatus: "needs_clarification" | "ready" | "committed" | "expired";
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Current Revision */
            current_revision?: number | null;
            /** Field Errors */
            field_errors?: {
                [key: string]: string;
            } | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** Event */
        Event: {
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /** Event Id */
            event_id: string;
            /** Location */
            location: string | null;
            recurrence: components["schemas"]["Recurrence"] | null;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /** Title */
            title: string;
            /** Version */
            version: number;
        };
        /** EventPage */
        EventPage: {
            /** Items */
            items: components["schemas"]["Event"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** FlexibleTask */
        FlexibleTask: {
            /** Deadline */
            deadline: string | null;
            /** Deadline Precision */
            deadline_precision: ("date" | "instant") | null;
            /** Task Id */
            task_id: string;
            /** Timezone */
            timezone: string;
            /** Title */
            title: string;
            /** Version */
            version: number;
        };
        /** FlexibleTaskQueryRequest */
        FlexibleTaskQueryRequest: {
            /** Conversation Id */
            conversation_id: string;
            /** Query Scope */
            query_scope: string;
            /** Source Message Id */
            source_message_id: string;
        };
        /** FlexibleTaskQueryResponse */
        FlexibleTaskQueryResponse: {
            /** Items */
            items: components["schemas"]["FlexibleTask"][];
            /** Source Message Id */
            source_message_id: string;
        };
        /** FlexibleTaskRequest */
        FlexibleTaskRequest: {
            /** Deadline */
            deadline: string | null;
            /** Deadline Precision */
            deadline_precision: ("date" | "instant") | null;
            /** Source Message Id */
            source_message_id: string;
            /** Timezone */
            timezone: string;
            /** Title */
            title: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** MessagePage */
        MessagePage: {
            /** Draft Refs */
            draft_refs: string[];
            /** Items */
            items: components["schemas"]["ConversationMessage"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** MessageRequest */
        MessageRequest: {
            /** Client Message Id */
            client_message_id: string;
            /** Content */
            content: string;
            /** Expected Sequence */
            expected_sequence: number;
            /** Timezone */
            timezone: string;
        };
        /** MessageResponse */
        MessageResponse: {
            answer: components["schemas"]["ConversationMessage"];
            /** Draft Refs */
            draft_refs: string[];
            /** Revision */
            revision: number;
            /** Tool Results */
            tool_results: {
                [key: string]: unknown;
            }[];
        };
        /** Occurrence */
        Occurrence: {
            disposition: components["schemas"]["Disposition"];
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /** Event Id */
            event_id: string;
            /** Location */
            location: string | null;
            /** Occurrence Id */
            occurrence_id: string;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            temporal_phase: components["schemas"]["TemporalPhase"];
            /** Title */
            title: string;
            /** Version */
            version: number;
        };
        /** OccurrenceExceptionRequest */
        OccurrenceExceptionRequest: {
            /** Expected Version */
            expected_version: number;
            /** Source Action Id */
            source_action_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "excused" | "cancelled";
        };
        /** OccurrencePage */
        OccurrencePage: {
            /** Items */
            items: components["schemas"]["Occurrence"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Recurrence */
        Recurrence: {
            /** Dst Fold Policy */
            dst_fold_policy: ("earlier" | "later") | null;
            /** Dst Gap Policy */
            dst_gap_policy: "skip" | null;
            /** Ends On */
            ends_on: string | null;
            /**
             * Frequency
             * @enum {string}
             */
            frequency: "daily" | "weekly";
            /** Starts On */
            starts_on: string;
            /** Timezone */
            timezone: string;
            /** Weekdays */
            weekdays: number[] | null;
        };
        /** Reminder */
        Reminder: {
            /** Acknowledged At */
            acknowledged_at: string | null;
            /** Occurrence Id */
            occurrence_id: string;
            /** Reminder Id */
            reminder_id: string;
            /** Schedule Revision */
            schedule_revision: number;
            /** Version */
            version: number;
        };
        /** ReminderAckRequest */
        ReminderAckRequest: {
            /** Expected Version */
            expected_version: number;
            /** Schedule Revision */
            schedule_revision: number;
        };
        /** StateResponse */
        StateResponse: {
            /** Active Occurrences */
            active_occurrences: components["schemas"]["Occurrence"][];
            /** Conflicts */
            conflicts: components["schemas"]["Conflict"][];
            /** Due Reminders */
            due_reminders: components["schemas"]["Reminder"][];
            /** Next Transition At */
            next_transition_at: string | null;
            /**
             * Server Now
             * Format: date-time
             */
            server_now: string;
            /** State Revision */
            state_revision: number;
        };
        /**
         * TemporalPhase
         * @enum {string}
         */
        TemporalPhase: "upcoming" | "active" | "ended";
        /** WeatherObservation */
        WeatherObservation: {
            /** Cloud Cover */
            cloud_cover: number | null;
            /** Condition */
            condition: ("clear" | "partly_cloudy" | "overcast" | "rain" | "fog" | "snow") | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "current" | "forecast";
            /** Observed At */
            observed_at: string | null;
            /** Precipitation */
            precipitation: number | null;
            /** Valid Until */
            valid_until: string | null;
            /** Visibility */
            visibility: number | null;
        };
        /** WeatherResponse */
        WeatherResponse: {
            /**
             * Availability
             * @enum {string}
             */
            availability: "available" | "stale" | "unavailable";
            /** Fetched At */
            fetched_at: string | null;
            /** Location Id */
            location_id: string;
            /** Observations */
            observations: components["schemas"]["WeatherObservation"][];
            /** Source */
            source: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    decide_conflict_api_v1_conflict_decisions_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConflictDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictDecisionResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    conversation_api_v1_conversations_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_messages_api_v1_conversations__conversation_id__messages_get: {
        parameters: {
            query?: {
                cursor?: string | null;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    send_message_api_v1_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_draft_api_v1_drafts_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_draft_api_v1_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_draft_api_v1_drafts__draft_id__patch: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    clarify_api_v1_drafts__draft_id__clarifications_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClarificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    commit_draft_api_v1_drafts__draft_id__commit_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftCommitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftCommitResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    change_proposal_api_v1_event_change_proposals_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeProposalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeProposalResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    events_api_v1_events_get: {
        parameters: {
            query?: {
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    flexible_query_api_v1_flexible_task_queries_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlexibleTaskQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlexibleTaskQueryResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    flexible_task_api_v1_flexible_tasks_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlexibleTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlexibleTask"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    occurrences_api_v1_occurrences_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OccurrencePage"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    occurrence_exception_api_v1_occurrences__occurrence_id__exceptions_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                occurrence_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OccurrenceExceptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Occurrence"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ack_api_v1_reminders__reminder_id__ack_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                reminder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderAckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    state_api_v1_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    weather_api_v1_weather_get: {
        parameters: {
            query: {
                location_id: string;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
